### ISSUE TITLE
Ты пользуешься Edge браузером?

### ISSUE THREAD

**Issue by redveronika** [DevilARCC/PortfolioTask#1]
почему ты добавил эту строчку?
` <meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by UniverseArc** [comment]
А, ох х">
Нет, на самом деле)

Эта строчка указана в шаблоне, который я всегда прописываю при создании нового html документа х">
Честно, даже и не замечал её раньше..
(Шаблон этот уже был вшит в VS CODE, так сказать из коробки))
Вот гиф)

Но вообще, насколько знаю, с капризами EDGE'а при создании кода тоже желательно считаться, ибо им тоже кто-то пользуется xd, а он достаточно вредный.
P.S. Извиняюсь за качество :(

![2021-11-05 21-30-40 (1)](https://user-images.githubusercontent.com/93486544/140561756-505ab2b4-e05a-4004-b702-6b545aba4dae.gif)
